services:
  client:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    ports:
      - 80
    depends_on:
      - server

  server:
    build:
      context: ./server
      network: host
      dockerfile: Dockerfile
    ports:
      - 3333
    environment:
      - CHOKIDAR_USEPOLLING=true
