services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "82:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server:/app
      - /app/node_modules
